### ISSUE TITLE
Unbounded height when scrollDirection is horizontal

### ISSUE THREAD

**Issue by AviKenz** [quentin7b/flutter_grouped_listview#2]
First of all thanks for this great library. It's helping me a lot in my project.

When i set `scrollDirection: Axis.horizontal` i get the following: `'constraints.hasBoundedWidth': is not true`.
I even tried to constaint the parent (Container/Sizedbox) of the listview by setting a width and/or height to a fix double but it didn't help.

Here a sample code to reproduce the error:
```
  Widget _buildTest() {
    return GroupedListView<String, String>.list(
      scrollDirection: Axis.horizontal,
      items: List.generate(5, (index) => "Item $index"),
      headerBuilder: (_, name) => Text(name),
      listItemBuilder: (_, __, ___, name) => Text(name),
      itemGrouper: (name) => "",
    );
  }
```
Thanks for your feedback beforehand.

**Comment by qk7b** [comment]
Hi !
Thanks for using this :D I'm glad it helps you.
I'll have a look at this asap. 

What are you trying to achieve exactly ? A groupedlistview but in a row instead of a column ?

**Comment by qk7b** [comment]
I was being able to reproduce and I think I might found the issue (and therefore a fix).
Can you confirm that this is the expected behaviour ?

![output](https://user-images.githubusercontent.com/2990298/151797129-c51a78df-e6ae-4fef-bca6-4ea337fd31e3.gif)

**Comment by AviKenz** [comment]
Hello,

yeah it works !

Thank you so much (also for the speedy reply)
