### ISSUE TITLE
Remove extra padding around widget

### ISSUE THREAD

**Issue by adamcastleman** [quentin7b/flutter_grouped_listview#7]
Sorry, figured this out.

**Comment by adamcastleman** [comment]
Actually, did not figure this out...

There seems to be some padding somewhere that is surrounding the header. Can't figure out how to turn it off.

If you just drop the grid into two containers, you get padding between the top of the widget and the beginning header. This padding does not exist at subsequent headers:

Beginning of widget:
![IMG_2817](https://user-images.githubusercontent.com/65034505/208036205-11400dc8-9039-473e-8bb0-5699665187a2.png)

Second Header (No Padding):
![IMG_2818](https://user-images.githubusercontent.com/65034505/208036241-7fcf8f41-52d1-4355-b3f1-22e3362647a2.png)


If you try to manipulate the padding of the grid view, by setting EdgeInsets.zero, it adds the padding between the header and the actual grid, and adds a ton of padding between the other headers.

Beginning of grid
![IMG_2819](https://user-images.githubusercontent.com/65034505/208036274-829d7ba1-2178-4f8b-9ce5-b7e77d167f13.png)


Second Header
![IMG_2820](https://user-images.githubusercontent.com/65034505/208036283-cba1c045-92e7-4681-863c-f1d3b87cb67c.png)


This extra padding at the beginning is hurting my UI. Please advice. Thank you

Minimum code to reproduce
`Column( 
children: [ Container( height: MediaQuery.of(context).size.height * 0.333, color: Colors.blue, ), Container( height: MediaQuery.of(context).size.height * 0.666, color: Colors.red, child: GroupedListView.grid( padding: EdgeInsets.zero, crossAxisCount: 3, itemsAspectRatio: 1 / 1.1, items: List<int>.generate(100, (index) => index + 1), itemGrouper: (int i) => i.isEven, headerBuilder: (context, bool isEven) => Container( color: Colors.white, child: Text( isEven ? 'Even' : 'Odd', style: const TextStyle(fontWeight: FontWeight.bold), ), ), gridItemBuilder: (context, int countInGroup, int itemIndexInGroup, int item, int itemIndexInOriginalList) => Container( padding: const EdgeInsets.all(8), child: Card( color: Colors.white, child: Text(item.toRadixString(10), textAlign: TextAlign.center)), ), ), ), ], ),Column( children: [ Container( height: MediaQuery.of(context).size.height * 0.333, color: Colors.blue, ), Container( height: MediaQuery.of(context).size.height * 0.666, color: Colors.red, child: GroupedListView.grid( padding: EdgeInsets.zero, //or just not including padding crossAxisCount: 3, itemsAspectRatio: 1 / 1.1, items: List<int>.generate(100, (index) => index + 1), itemGrouper: (int i) => i.isEven, headerBuilder: (context, bool isEven) => Container( color: Colors.white, child: Text( isEven ? 'Even' : 'Odd', style: const TextStyle(fontWeight: FontWeight.bold), ), ), gridItemBuilder: (context, int countInGroup, int itemIndexInGroup, int item, int itemIndexInOriginalList) => Container( child: Card( color: Colors.white, child: Text(item.toRadixString(10), textAlign: TextAlign.center)), ), ), ), ], ),`

**Comment by qk7b** [comment]
Interesting.

I can't run your code, can you edit and format it an flutter understandable way ? Using

```
> ```dart
> ```
```

**Comment by adamcastleman** [comment]
Turned out to be totally unrelated to the package. Sorry!!
